### PR TITLE
Early Exploration on Distributed Block Builder Designs

### PR DESCRIPTION
**Pull request by ghiliweld**
Research proposal to define distributed block building, establish desiderata and criteria such distributed builders must fulfill  and explore possible distributed builder schemes.

### CODE REVIEW

**Comment by sarahalle** [comment]
Thanks for submitting this proposal @ghiliweld! We are reviewing it and will get back to you with any questions

**Comment by jopasserat** [comment]
Hello @ghiliweld thanks for submitting this very interesting proposal!

I like the overall outline for a potential paper, but in terms of scope for the FRP, I'd suggest you focus on points 5-8 and make sure you do propose designs.  

In terms of desiderata and constraints for a decentralised builder protocol, there're two important points (that you might already be aware of) that I would love to see in the study:
  - geographic decentralisation -> https://collective.flashbots.net/t/decentralized-crypto-needs-you-to-be-a-geographical-decentralization-maxi/1385
  - and the impact of danksharding on the technical feasibility of block building (since the plan is to push more work on block builders)

**Comment by ghiliweld** [comment]
Thank you for the feedback @jopasserat, I went ahead and edited the FRP with your comments in mind!

**Comment by sarahalle** [comment]
Thanks for these proposal updates @ghiliweld! We are excited about this project and want to fund it. I will accept and rename it to FRP-37! Please reach out to me via email at sarah.allen@flashbots.net, so that we can put together the grant agreement

**Pull request merged**
