### PR TITLE
Flashbots Research Proposal: Zero-knowledge proofs of FHE for MEV on Private Transactions

### PR DESCRIPTION
**Pull request by 5hadv**

### CODE REVIEW

**Comment by 5hadv** [comment]
@jopasserat

**Comment by sarahalle** [comment]
Thanks for submitting this proposal @5hadv! We are reviewing it and will get back to you with any questions

**Comment by jopasserat** [comment]
Hey! Thanks a lot for the proposal!

I don't have write access to neither this PR nor your fork @5hadv so I made some changes on the following hackmd, if you could please integrate them: https://hackmd.io/1hbq9YW2RuCnHR-V5qceCg

Just a few clarification points in addition to these changes:

- [ ] can you give some pointers on how hard the implementation phase will be?
- [ ] which building blocks are readily available vs need to be written from scratch?
- [ ] I assume the language will be Rust and involve arkworks?

Great stuff overall!

**Comment by 5hadv** [comment]
Hey

> Hey! Thanks a lot for the proposal!
> 
> I don't have write access to neither this PR nor your fork @5hadv so I made some changes on the following hackmd, if you could please integrate them: https://hackmd.io/1hbq9YW2RuCnHR-V5qceCg
> 
> Just a few clarification points in addition to these changes:
> 
> * [ ]  can you give some pointers on how hard the implementation phase will be?
> * [ ]  which building blocks are readily available vs need to be written from scratch?
> * [ ]  I assume the language will be Rust and involve arkworks?
> 
> Great stuff overall!

Awesome, thanks. I added your updates in the HackMD to the repo. I also included the answers to your questions, I added hourly estimates to each task. These are estimates based on my prior knowledge of each task. You are correct that I will be using Rust. I think either arkworks or something like Plonky3 could work - but for standardizing with the research community, maybe arkworks is better.

**Comment by sarahalle** [comment]
Hi @5hadv- thanks for submitting this proposal! We are excited about this project and want to fund your work. Please reach out to me at sarah.allen@flashbots.net for the grant agreement process.

**Comment by sarahalle** [comment]
Hi @5hadv - I went to accept this FRP, but I realized that you edited the FRP template rather than submitting your proposal as a new FRP to the FRP folders. Could you please resubmit the proposal following that format (create a new FRP based on the template rather than replacing it and submit it to the FRP folder)? Once you submit that, I can accept the proposal

**Pull request merged**
