### PR TITLE
Create proposal-mechanisms_of_blockchain_based_darkpools.md

### PR DESCRIPTION
**Pull request by yusufxzy**

### CODE REVIEW

**Comment by sarahalle** [comment]
Hi @yusufxzy- thanks for submitting this proposal! We will review it and get back to you with feedback or questions

**Comment by goldnutter** [comment]
Can someone please call my brother on zero four two four seven four eight
two five seven or text him please pick up Gavin from Midland mental health
I do not belong here.  H help help

**Comment by yusufxzy** [comment]
> Hi @yusufxzy- thanks for submitting this proposal! We will review it and get back to you with feedback or questions

Thank you! Looking forward to it.

**Comment by jopasserat** [comment]
Hello @yusufxzy 

Thanks for submitting your proposal. I took the time to review your DarkPool as well for context. Here are some comments:

- I assume that the items "Survey dark pool teams" and "Establish Desired Properties of Dark Pools" will mostly be a summary of the previous post with minor changes?
- We might be able to help assist with "The survey of teams and users"
- The "Quantitative analysis" bit seems like one of the most interesting contribution in the FRP. Would you be able to flesh out the methodology a bit more? I'm a bit concerned this might require significant capital for instance?
- "Highlight points of information leakage that could lead to MEV extraction" -> yes but we should also see the positive side: what would it look (maybe some folks are already doing it) to auction off the right to backrun the on-chain settlement of a dark pool to searchers? Or similarly, are there already evidence of searchers providing liquidity in dark pools?

**Comment by yusufxzy** [comment]
> Hello @yusufxzy
> 
> Thanks for submitting your proposal. I took the time to review your DarkPool as well for context. Here are some comments:
> 
> * I assume that the items "Survey dark pool teams" and "Establish Desired Properties of Dark Pools" will mostly be a summary of the previous post with minor changes?
> * We might be able to help assist with "The survey of teams and users"
> * The "Quantitative analysis" bit seems like one of the most interesting contribution in the FRP. Would you be able to flesh out the methodology a bit more? I'm a bit concerned this might require significant capital for instance?
> * "Highlight points of information leakage that could lead to MEV extraction" -> yes but we should also see the positive side: what would it look (maybe some folks are already doing it) to auction off the right to backrun the on-chain settlement of a dark pool to searchers? Or similarly, are there already evidence of searchers providing liquidity in dark pools?



Hi @jopasserat 

Thank you for taking the time to review and give feedback.

1. "Survey dark pool teams" and "Establish Desired Properties of Dark Pools" will include insights from the previous post, but I also aim to go into more detail regarding their design choices across PETs, DEX design, settlement methods, etc
2. Awesome! That would be of much help.
3. Yes. I will execute orders on mainnnet on the dark pools that are live, testnet for those that are not live. This would help me get numbers on latency and settlement. I will work with dark pool teams to help benchmark costs & time with regards to using PETs. Surveying teams & users will help determine the quality of pricing, especially for large trades. I am in touch with a few liquid funds and market makers that would help benchmark these metrics. 
4. Interesting point! this could be an added consideration for some new and existing designs!! Yes, not searchers exactly, but solvers who help fulfill orders are a part of some dark pool designs.

**Comment by tesaho** [comment]
Hey @yusufxzy!

Adding my comments:

1. "Blockchain-based dark pools on the other hand, aim to abstract the need for trust in a single operator". I would say liquidity and privacy are the biggest reason for using dark pools.

2. "
- How "dark" are these blockchain-based dark pools?
- Can they effectively mitigate risks related to MEV, collusion, trust parties, and information asymmetry?
- If the order flow routing off of dark pools is to settle on Ethereum, how do its privacy guarantees hold up at the block building and settling periods?
- If the order flow is routing off of L2s, can the L2’s sequencer have a peak at its order flow?"

- It would be interesting to compare what each market reveals (if anything) in their dark pools for each order.  Assuming that the order flow is coming from funds and the counterparties are market makers / funds.
- How would you measure this?  Would you look at the txn published to the blockchain and look for atomic arb?  Would you be able to quantify CEX-DEX arb?
- Do you mean you will explain how the off-chain execution is settled on Mainnet?  Are they routing the txn through a private mempool or directly to a builder?
- Why is the dark pool operator settling on L2 instead of L1?  Latency? Cost? Funding arrangement?

3) "- Quantitative analysis of
    - latency & Settlement
    - Proof generation costs & time
    - Quality of pricing"
 
- How would you measure the latency between the off-chain match and on-chain settlement?  If your order is sitting in the dark pool (i.e. limit order), are you measuring the time the order is matched to builder block inclusion or sequencer inclusion?  Would you be able to identify order matching time in a dark pool?  If you donʻt have an order matching time, how would you estimate the pricing quality (block inclusion / sequencer time vs cex pricing?)?
- I would also look at transaction volumes of pairs, transaction counts, number of pairs traded, and slippage (trading costs + execution slippage).
 
 4) Qualitative questions:
 - how are you evaluating privacy pre-execution and post-execution?

**Comment by yusufxzy** [comment]
1. **"Blockchain-based dark pools, on the other hand, aim to abstract the need for trust in a single operator. I would say liquidity and privacy are the biggest reason for using dark pools."**
Correct. Liquidity and privacy are essential for dark pools in tradfi and crypto. One way in which they both differ is the role of an operator. Tradfi dark pools have a single operator, whereas the level of trust in crypto dark pools is variable. 

2. **"It would be interesting to compare what each market reveals (if anything) in their dark pools for each order. Assuming that the order flow is coming from funds and the counterparties are market makers / funds."**
- Yes. Keen on seeing how order matching affects quality of pricing across markets.

- **"How would you measure this? Would you look at the txn published to the blockchain and look for atomic arb? Would you be able to quantify CEX-DEX arb?"**
I would evaluate their designs to see the flow of transactions, whether third parties or relayers handle them, and whether they could examine order information depending on how PETs are used in the order cycle. My question would seek to answer if at all value could be extracted in each design and, if so, how it could be done. Quantifying MEV in dark pools would be a topic to look into soon. 
 
* **"Do you mean you will explain how the off-chain execution is settled on Mainnet? Are they routing the txn through a private mempool or directly to a builder?"**
- Yes. I will look into these details for each design as it determines who gets to look at order information if bad MEV can be extracted, and if privacy is compromised towards the end of the txn supply chain. This is especially important given that major Builders/Searchers also operate as Market Makers who may be "helping" match orders on dark pools. I will also look at potential solutions, such as encrypted mempools that ensure user protection even at the builder level. 

* **"Why is the dark pool operator settling on L2 instead of L1? Latency? Cost? Funding arrangement?"**
- Yes. Latency and costs are major factors for building on an L2. Renegade, for example, is on Arbitrum One. Arbitrum currently uses FCFS, but if and when Timeboost is implemented, it will open up the L2 scene for other types of MEV as searchers are allowed to build bundles. So, the choice of L2 or L1 influences levels of privacy, latency, costs, etc.

3. **"How would you measure the latency between the off-chain match and on-chain settlement? If your order is sitting in the dark pool (i.e., limit order), are you measuring the time the order is matched to builder block inclusion or sequencer inclusion? Would you be able to identify order matching time in a dark pool? If you donʻt have an order matching time, how would you estimate the pricing quality (block inclusion/sequencer time vs cex pricing?)?"**
- Latency would be between when an order has found a match to the builder and sequencer inclusion. 
- I will choose the most liquid asset in a particular dark pool to ensure there are no delays in execution.
- There should be a transaction explorer for each design that is live or in testnet. This would help put a number on latency. Additionally, I will work with dark pool teams to help get accurate numbers. 

* **"I would also look at transaction volumes of pairs, transaction counts, number of pairs traded, and slippage (trading costs + execution slippage)."**
- Right. These metrics are good to look at once dark pools have gone live, enabling the trading of various pairs. 


4. **"how are you evaluating privacy pre-execution and post-execution?"**
- **Pre execution privacy** 
-- In each design, who manages orders? how are they matched? Who learns about them? Who is trusted? Given their design, are there technical or economic attack vectors that could compromise privacy?
- **Post-execution privacy**
-- Once orders are matched and sent for execution, who is trusted not to peek in or leak order info? Does the dark pool design keep individual trades private even after execution? What policy or method do they follow regarding post-execution information disclosure?

**Comment by jopasserat** [comment]
great discussion!
@yusufxzy can you please revise the proposal with the above comments so that we review the final form and make a decision based on this new content?

**Comment by yusufxzy** [comment]
Got it. I've made changes to the FRP based on our discussion @jopasserat

**Comment by sarahalle** [comment]
Hi @yusufxzy- sorry for the slow processing on this proposal. We are excited about this project and want to fund your work! @jopasserat will serve as monitor. I will accept and rename it to FRP-44. Please reach out to me at sarah.allen@flashbots.net to coordinate contracting.

**Pull request merged**
