### PR TITLE
Frequent Batch Auction on SUAVE

### PR DESCRIPTION
**Pull request by Cassiopeia1115**
Submitting a draft FRP on Frequent Batch Auction on SUAVE

### CODE REVIEW

**Comment by sarahalle** [comment]
Thanks for submitting this proposal! We are reviewing it and will get back to you with questions or feedback

**Comment by Cassiopeia1115** [comment]
Ok, Thanks.

**Comment by sergioyuhjtman** [comment]
Thanks for submitting! The general topic is of interest. The most important deliverable of the proposal is an empirical analysis of different market designs. However it does not mention specific questions and methods to this end. Thus it is not clear how the proposal differs from previous and ongoing work in the area.

**Comment by sarahalle** [comment]
Thanks for submitting this proposal @Cassiopeia1115!  While FBAs are of general interest to us, we are not able to prioritize funding and collaborating on this project. As @sergioyuhjtman mentioned in his comment, the proposed project would have general contributions to theory, but we are not able to assess the unique contributions as compared to existing and ongoing work. Some related work mentioned by our team in reviewing the proposal are FRP-40 (proposal in the active folder, outcome to be posted soon to https://collective.flashbots.net/c/frp/24) and auction theory work from the CoWswap team.

**Pull request closed without merging**
