### PR TITLE
Create franklindao-l2-mev-research

### PR DESCRIPTION
**Pull request by austin-yao**
Research proposal for on L2 MEV and parallels to possible strategies in cross-chain bridging front-running

### CODE REVIEW

**Comment by austin-yao** [comment]
Thank you @sarahalle. Do you know when we can expect to hear back? We're happy to answer any questions or provide additional info.

**Comment by sarahalle** [comment]
Hi @austin-yao! Sorry for the delay- someone from Flashbots has fully reviewed the proposal and plans to comment with feedback in the next couple days.

**Comment by austin-yao** [comment]
Hi @0xYager, thanks for getting back! Your feedback about focusing on decentralizing sequencers within the current landscape makes a lot of sense, and we would be happy to move forward with the proposal with these changes. Do you have information on our next steps to get the grant underway?

**Comment by sarahalle** [comment]
Thanks @0xYager! @austin-yao, if you are happy with all those suggested directions, would you please update the proposal to reflect the updated focus? I will then merge the PR and formally accept the FRP. We will then get a communication set up for your collaboration with @0xYager within Flashbots and coordinate the grant funding :)

**Comment by austin-yao** [comment]
@sarahalle Thanks! The proposal should be updated to reflect a new focus on decentralizing L2 sequencers. We're happy to move forward, and let us know if we can supply more information in the meantime.

**Comment by sarahalle** [comment]
Thanks @austin-yao! I will merge the PR and accept this FRP 🎉 @0xYager will be your internal contact at Flashbots for this project. Please reach out to me at sarah.allen@flashbot.net, so that we can get the contract and grant in progress.

**Pull request merged**
