### PR TITLE
added the proposal proposal-MEV_as_UBI.md

### PR DESCRIPTION
**Pull request by SoweluAvanzo**
I am submitting the file proposal-MEV_as_UBI as an application for funding as a member of Circles UBI, based on the indicaitons provided in the template document.

### CODE REVIEW

**Comment by sarahalle** [comment]
Thanks for submitting this FRP @SoweluAvanzo! We will review it and get back to you with any questions.

**Comment by sarahalle** [comment]
Adding a comment here to note that researcher from our team reached out via email to discuss resubmission of the proposal as two separate projects. We are interested in supporting and collaborating on this work, but we would like to see it rescoped to ensure it can succeed :)

**Comment by sarahalle** [comment]
I'm closing this current proposal due to inactivity, but hope to see it resubmitted as a multi-part project later on :)

**Comment by SoweluAvanzo** [comment]
Dear Sarah,
many thanks for your kind update.  We are currently working on the
resubmission of the first part of the proposal. We currently have a draft
<https://docs.google.com/document/d/1aHBujHgdFP9iuNljUib6idBzk7xb4_GNe0V6QYCJtRw/edit?usp=sharing>,
and are engaging in internal coordination in order to ensure that we
achieve an optimal result during the project execution. Soon we will have a
version of it that is ready for resubmission.
Kind regards,
Sowelu

Il giorno mar 23 gen 2024 alle ore 23:44 Sarah Allen <
***@***.***> ha scritto:

**Pull request closed without merging**
