### PR TITLE
Create proposal-mev_bidding_Shalpley.md

### PR DESCRIPTION
**Pull request by magnetar-iiith**

### CODE REVIEW

**Comment by sarahalle** [comment]
Thanks for submitting this proposal! We are reviewing it and will get back to you with any questions or feedback

**Comment by magnetar-iiith** [comment]
@sarahalle thank you for putting the proposal for the review. May we know if there is any update on this? Thanks

**Comment by sarahalle** [comment]
Hi @magnetar-iiith! We reviewed this proposal and are aware of some work in progress that overlaps. Let's get on a call to discuss. Please reach out to me at sarah.allen@flashbots.net and we can coordinate there.

**Comment by magnetar-iiith** [comment]
Thanks @sarahalle. We have emailed you for meeting slots. We hope you got it. We will wait for you to get back to us.

**Comment by sarahalle** [comment]
Thank you for submitting this proposal! Unfortunately we don't have internal bandwidth to collaborate on this project, so we aren't able to accept this FRP

**Pull request closed without merging**
