### PR TITLE
Create Draft for FRP-43.md

### PR DESCRIPTION
**Pull request by benber86**
Draft for FRP on the question: Can Sandwich Attacks Benefit their Victims?

### CODE REVIEW

**Comment by facuzeta** [comment]
Your proposal raises an intriguing question, and I find your perspective to be quite innovative! I have some questions that I believe your responses could assist me in better understanding your proposal:


1. Is all the necessary data for setting up the dataset available on-chain, or would off-chain data be required?

2. Will the data collection focus on future data or past data? If it pertains to past data, what is your strategy for acquiring off-chain data, if needed?

3. How do you intend to gather the required data?

4. Which DEX do you plan to commence with?

5. Additionally, which other DEXs do you believe are feasible targets for expansion?

6. What would be the dataset size required to achieve the stated objective?

7. Could you propose an estimated timeline for the tasks outlined in the plan section?

Thanks!

**Comment by benber86** [comment]
Thanks for the question:

> 1. Is all the necessary data for setting up the dataset available on-chain, or would off-chain data be required?

We're only planning to look at on-chain sandwiches using on-chain prices, so we won't be using off-chain data.

> 2. Will the data collection focus on future data or past data? If it pertains to past data, what is your strategy for acquiring off-chain data, if needed?

Only past data. Data acquisition strategy is a mix of our own indexing tools, subgraphs, and potentially existing datasets (from the flashbots repo for instance) if we find some that are relevant.

> 3. How do you intend to gather the required data?

As mentioned above, a mix of homemade tools (in Typescript, Python with web3py) subgraphs for indexing and further post-processing with TS and/or Python to parse transaction traces and detect sandwiches. We store all the data in a PostgreSQL database. We will then filter the relevant data (sandwich trades with metadata) and release this publicly in a CSV format.

> 4. Which DEX do you plan to commence with?

We will start with Curve as we already have a good amount of comprehensive trade data for it.

> 5. Additionally, which other DEXs do you believe are feasible targets for expansion?

We plan to look at Uniswap v2 pools on Uniswap and Sushi on mainnet. We might look into Uniswap v3 but that depends on the complexity of setting up 

> 6. What would be the dataset size required to achieve the stated objective?

We expect the original raw data to be in the 100 gigabytes range as we will be tracking all trades on multiple DEXes. Sandwiches are only a subpart of these however so that dataset would be smaller. Profitable sandwiches are an even smaller subset and we don't expect a dataset that would only contain those to exceed 1 gigabyte.

> 7. Could you propose an estimated timeline for the tasks outlined in the plan section?
- Data collection, methodology for detection and parsing data for Curve trades: 1 month
- Outline mechanisms and typology: 1 month
- Formal model: 1 month
- Expand detection to other Uniswap/Sushi (v2 pools), collect and analyze data: 2 months
- Estimate prevalence chain-wide, finalize writings summarizing findings, clean up and publish datasets: 1 months

Total: 6 months

**Comment by facuzeta** [comment]
Amazing! Thank you for answering my questions.

**Comment by sarahalle** [comment]
Thanks for submitting this proposal @benber86! We are excited about this project and would like to fund your work. 
I'll accept it as FRP-43. Please reach out to me at sarah.allen@flashbots.net, so that we can move forward the grant agreement.

**Pull request merged**
