### PR TITLE
Flashbots Research Proposal: App-level MEV Capture - Lending Protocols

### PR DESCRIPTION
**Pull request by arnx813**

### CODE REVIEW

**Comment by elenahoo** [comment]
Thanks for the proposal, it's an interesting area to look into. I'd like to understand a bit more details regarding some of the points mentioned in the proposal: 
- Do you have any specific orderbook exchanges you plan to look into and on which chains? 
- How do you plan to get the data needed for the analysis i.e. bid-ask spread, orderbook depth etc. are these all available to collect on chain?
- Are the details of matching algorithms and pricing mechanisms for these lending protocol available to the public, i.e. open-source code for the algos they use?
- How do you define "toxic flow"? The liquidator bots take a discount from the lending protocol to sell these collaterals on behalf of them under extremely volatile market condition because there's a huge risk of sudden price drop. So they get compensated for taking such risks. It's not always the case the liquidation bots get to sell to the users at a higher than market price, making the execution worse for the users. I think it's more often that they bought the assets (collaterals) at a discount, and sell at market price to make a profit.
- Have you looked into the design of https://kujira.network/liquidate? They provide the platform for users to buy collaterals at a discount, so removing the need of liquidation bots from the equation

**Comment by arnx813** [comment]
> Thanks for the proposal, it's an interesting area to look into. I'd like to understand a bit more details regarding some of the points mentioned in the proposal:
> 
> * Do you have any specific orderbook exchanges you plan to look into and on which chains?
> * How do you plan to get the data needed for the analysis i.e. bid-ask spread, orderbook depth etc. are these all available to collect on chain?
> * Are the details of matching algorithms and pricing mechanisms for these lending protocol available to the public, i.e. open-source code for the algos they use?
> * How do you define "toxic flow"? The liquidator bots take a discount from the lending protocol to sell these collaterals on behalf of them under extremely volatile market condition because there's a huge risk of sudden price drop. So they get compensated for taking such risks. It's not always the case the liquidation bots get to sell to the users at a higher than market price, making the execution worse for the users. I think it's more often that they bought the assets (collaterals) at a discount, and sell at market price to make a profit.
> * Have you looked into the design of https://kujira.network/liquidate? They provide the platform for users to buy collaterals at a discount, so removing the need of liquidation bots from the equation

**Q. Do you have any specific order book exchanges you plan to look into and on which chains?** 

Our primary focus with this research will be on Hyperliquid. However, it will also apply to dYdX and additional orderbook exchanges to come including GTE on MegaETH and Kuru on Monad. The focus will be on newer orderbook exchange designs, particularly the on-chain spot orderbooks that are coming out.

As mentioned from our original proposal, we think spot order books are particularly interesting for a few reasons:
They will become a new liquidation venue for lending protocols, potentially offering better price execution UX.
Due to their newness, their MEV dynamics and market structure are unclear, requiring more exploration and analysis.

**Q. How do you plan to get the data needed for the analysis i.e. bid-ask spread, orderbook depth etc. are these all available to collect on chain?** 

Yes, comprehensive data for all order types is available on-chain. Certain chains, like Hyperliquid, provide historical data through their [APIs](https://hyperliquid.gitbook.io/hyperliquid-docs/historical-data). If needed, we can set up a dedicated read node to gather any missing data for a more thorough analysis. For example, we can spin up an archive node on Monad using Geth. Then we can set up our own blockchain indexer for indexing all the events related to the orderbook exchange Kuru; we can then save the indexed data onto a porstgres database. Once this is accomplished we can then go on to generate the time series historical data using all the buy/sell/modify orders from the indexed data. 

**Q. Are the details of matching algorithms and pricing mechanisms for these lending protocols available to the public, i.e. open-source code for the algos they use?** 

While the exact algorithms for these protocols aren't open-source, there are established standard algorithms that can be applied to simulate order flow within an orderbook structure. One such algorithm we can implement for this research is the Pro-Rata algorithm which matches orders based on their price, time & quantity. In this algorithm, orders are allocated based on their percentage of the total order quantity at a particular price level. For example, if there are two buy orders for 100 shares and 200 shares at a particular price level, the matching engine will allocate 33.3% to the first order and 66.7% to the second order.

**Q. How do you define "toxic flow"? The liquidator bots take a discount from the lending protocol to sell these collaterals on behalf of them under extremely volatile market conditions because there's a huge risk of sudden price drop.**


Toxic flow generally refers to instances where a participant observes a large order, removes liquidity from that level, and repositions it at a higher price in the absence of competing orders. This approach is particularly impactful with market orders, as large orders often clear substantial liquidity at specific price levels and create price discrepancies. We are referring primarily to the arbitrage opportunities granted to liquidators after a large sale of collateral–this is MEV that can be captured by the lending protocol.


**Q. Have you looked into the design of https://kujira.network/liquidate? They provide the platform for users to buy collaterals at a discount, so removing the need of liquidation bots from the equation**

Yes, we are familiar with Orca by Kujira as well as direct liquidation auction systems like Pyth Express Relay, which we have worked with in the past. There is a reason that these systems have not been able to gain critical adoption for lending protocols. In PER’s case, the need (cross-chain liquidity and low slippage liquidations) is not met. The chain of the lending protocol is still required to have significant liquidity, and PER’s primary offering is additional liquidation bots. 

In Kujira Orca’s case, we think this idea of involving community members to purchase collateral is not fully realistic from an adoption standpoint, and it is why Orca has seen limited success at scale. Liquidation bots will continue to dominate liquidation flows in our opinion, so we want to research solutions that can help lending protocols capture that value back without attempting to eliminate liquidation bots. 

Part of this research will be to more concretely understand the design tradeoffs of Pyth’s PER, Uma’s Oval, and Kujira’s Orca to understand why they have not achieved mass adoption if their solutions accomplish what they propose and bring these findings into our final design (a focus of Weeks 5-7, directly with orderbook MEV specifically). Our ideal here is to determine the best mechanism that can be integrated into lending protocol and/or orderbook architecture directly.

**Comment by sarahalle** [comment]
Hi @arnx813! We are excited about this proejct and want to fund your work as an FRP. However, it looks like you have submitted this proposal incorrectly (as a replacement to the FRP template rather than a new proposal to the FRP folders based on that template, while keeping the template existing in the repo). Could you please resubmit this proposal correctly and we can then move it forward?

**Comment by arnx813** [comment]
Thanks for the update @sarahalle! I just added a new commit to my fork version, so it should be included in this PR. The proposal is currently in the active folder - is that where it's supposed to be? Let me know if everything looks good!

**Comment by sarahalle** [comment]
Thanks for updating the proposal! We are excited about this work and want to fund it. @elenahoo will be our contact within the Flashbots for the project. I will accept it as FRP-46 and merge it now. Look out for an email from me to set up the grant agreement

**Pull request merged**
